submitter:
  git.sr.ht:
    enabled: true
    allow-refs:
      - refs/heads/master
      - "refs/tags/*"


image: archlinux
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
- uv
environment:
  site: ayys.srht.site
tasks:
- package: |
    cd illegal-in-nepal
    make build
    tar cvzf site.tar.gz site/

- upload: |
    hut pages publish -d ayys.srht.site site.tar.gz
